### ISSUE TITLE
Release MUI-demo v1.0

### ISSUE THREAD

**Issue by Wendi-L** [MxUI/MUI-demo#17]
The MUI-demo should be released with the MUI main code with the same version number.

The recent updates on the MUI-demo (such as mui4py demos) cannot be run correctly by MUI-v1.0.

**Comment by SLongshaw** [comment]
Agreed, there needs to be a clear definition for the cases which MUI version number they require. All cases are tested against the current master branch, this is a requisite of any commit being accepted (albeit this isn't yet automated using CI as it hopefully will be soon), so they will all work using the most recent pull but that doesn't make it clear for those wishing to use defined releases of the library.

Suggestion: for each demo case, add a minimum version requirement of the MUI library to the README with the understanding that all tests are compiled against any new inclusion into the master branch and should requirements change it is up to the main library maintainer that is approving/performing the master branch change to also update requirements for the demos that require it. if this suggestion seems appropriate, I am happy to do this in the first instance so it can be maintained going forwards.

**Comment by Wendi-L** [comment]
Good suggestion. I can take care of the mui4py demos to add the minimum version requirement to their README.

**Comment by SLongshaw** [comment]
Ok, let me create a new point release in the next day or so and that can be the initial reference point to start from.

**Comment by SLongshaw** [comment]
I have now created a 1.1 release that all current demos will compile against. 

Please feel free to add comments to demos and update in the master branch and this can be maintained going forwards.

I will now close this as resolved.
